### ISSUE TITLE
ssh-audit [exception] [Errno 11003] getaddrinfo failed

### ISSUE THREAD

**Issue by Zaptyp** [jtesta/ssh-audit#165] opened 2023-03-04 22:43 UTC
I don't know why ssh-audit cannot connect to my ssh server and i get error
[exception] [Errno 11003] getaddrinfo failed

**Comment by egberts** [comment] 2023-03-05 15:49
If you cannot do a `tcptraceroute` with your correct SSH port number, and you get that error, then check your ping, route, and firewall.

**Comment by jtesta** [comment] 2023-03-14 21:26
@Zaptyp : can you create a TCP connection to the SSH server using the telnet or netcat clients?

**Comment by Zaptyp** [comment] 2023-03-14 22:00
Yes I can

**Comment by Zaptyp** [comment] 2023-03-15 06:11
@jtesta Timeout

**Comment by jtesta** [comment] 2023-03-20 22:29
@Zaptyp : Is the target host available via the public Internet?  If so, I'd like to debug this issue against it.  Please e-mail me its hostname/IP (jtesta at-sign positronsecurity dot com), if possible.  Thanks!

**Comment by jtesta** [comment] 2023-03-21 12:54
@Zaptyp : I ran ssh-audit from the master branch against the target multiple times, and it completed successfully each time.  What version of ssh-audit did you witness the error with?  Do you still get the error with the version in the master branch?

**Comment by Zaptyp** [comment] 2023-03-23 07:13
@jtesta Yes i still get the error

**Comment by jtesta** [comment] 2023-03-23 13:39
Do you have access to a cloud VM?  If so, can you reproduce it from there?

I'm not able to reproduce this error against your host, so I'm thinking this is a client network problem.

**Comment by sunwire** [comment] 2023-03-28 13:05
@Zaptyp Are you running ssh-audit on windows?. Run this code
```
import os
assert 'SYSTEMROOT' in os.environ

```
if it fails SYSTEMROOT is not set and probably this is why getaddrinfo fails

**Comment by Zaptyp** [comment] 2023-03-30 05:24
@sunwire Not fails

**Comment by Zaptyp** [comment] 2023-03-30 05:25
@jtesta Can you add more debug info to ssh-audit?

**Comment by jtesta** [comment] 2023-03-30 13:26
@Zaptyp : try running the following Python script from the same machine that you get the error on:

```
import socket
import sys


host = sys.argv[1]

for family in [socket.AF_UNSPEC, socket.AF_INET, socket.AF_INET6]:
    print("Trying family %u..." % family)
    result = socket.getaddrinfo(host, 22, family, socket.SOCK_STREAM)
    print(result)
    print()
```

It takes one command-line argument: the target host (use the same one that you get the ssh-audit error with).  Please copy/paste the entire result, and perhaps that will help us understand the problem.

**Comment by Zaptyp** [comment] 2023-03-30 15:25
@jtesta Output:
```
C:\Users\Zaptyp\Desktop>python "test (2).py" XXX.XXX.XXX.39
Trying family 0...
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('XXX.XXX.XXX.39', 22))]

Trying family 2...
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('XXX.XXX.XXX.39', 22))]

Trying family 23...
Traceback (most recent call last):
  File "C:\Users\Zaptyp\Desktop\test (2).py", line 9, in <module>
    result = socket.getaddrinfo(host, 22, family, socket.SOCK_STREAM)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed
```

**Comment by sunwire** [comment] 2023-03-30 18:17
@Zaptyp  Does  your hostname (localhost) contains non ASCII letters?

**Comment by Zaptyp** [comment] 2023-03-30 18:26
@sunwire Nope

**Comment by jtesta** [comment] 2023-03-30 23:20
@Zaptyp : When the error occurs, are you running ssh-audit using the `-6` argument at all?  If you use the `-4` option, does the error still occur?

**Comment by Zaptyp** [comment] 2023-03-31 05:15
@jtesta Parametr -6:
```
C:\Users\Zaptyp\Desktop\ssh-audit>python ssh-audit.py -6 xxx.xxx.xxx.xxx
[exception] [Errno 11001] getaddrinfo failed
```
Parametr -4 working but you need to fix this:
```
C:\Users\Zaptyp\Desktop\ssh-audit>python ssh-audit.py -4 xxx.xxx.xxx.xxx
# general
(gen) banner: SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.1
(gen) software: OpenSSH 8.9p1
(gen) compatibility: OpenSSH 8.5+, Dropbear SSH 2018.76+
(gen) compression: enabled (zlib@openssh.com)

# key exchange algorithms
(kex) sntrup761x25519-sha512@openssh.com    -- [info] available since OpenSSH 8.5
(kex) curve25519-sha256                     -- [info] available since OpenSSH 7.4, Dropbear SSH 2018.76
(kex) curve25519-sha256@libssh.org          -- [info] available since OpenSSH 6.5, Dropbear SSH 2013.62
(kex) diffie-hellman-group16-sha512         -- [info] available since OpenSSH 7.3, Dropbear SSH 2016.73
(kex) diffie-hellman-group18-sha512         -- [info] available since OpenSSH 7.3
(kex) diffie-hellman-group-exchange-sha256 (2048-bit) -- [warn] 2048-bit modulus only provides 112-bits of symmetric strength
                                                      `- [info] available since OpenSSH 4.4
                                                      `- [info] A bug in OpenSSH causes it to fall back to a 2048-bit modulus regardless of server configuration (https://bugzilla.mindrot.org/show_bug.cgi?id=2793)

# host-key algorithms
(key) rsa-sha2-512 (3072-bit)               -- [info] available since OpenSSH 7.2
(key) rsa-sha2-256 (3072-bit)               -- [info] available since OpenSSH 7.2
(key) ssh-ed25519                           -- [info] available since OpenSSH 6.5

# encryption algorithms (ciphers)
(enc) chacha20-poly1305@openssh.com         -- [info] available since OpenSSH 6.5
                                            `- [info] default cipher since OpenSSH 6.9.
(enc) aes256-gcm@openssh.com                -- [info] available since OpenSSH 6.2
(enc) aes128-gcm@openssh.com                -- [info] available since OpenSSH 6.2
(enc) aes256-ctr                            -- [info] available since OpenSSH 3.7, Dropbear SSH 0.52
(enc) aes192-ctr                            -- [info] available since OpenSSH 3.7
(enc) aes128-ctr                            -- [info] available since OpenSSH 3.7, Dropbear SSH 0.52

# message authentication code algorithms
(mac) hmac-sha2-256-etm@openssh.com         -- [info] available since OpenSSH 6.2
(mac) hmac-sha2-512-etm@openssh.com         -- [info] available since OpenSSH 6.2
(mac) umac-128-etm@openssh.com              -- [info] available since OpenSSH 6.2
```

**Comment by jtesta** [comment] 2023-03-31 13:56
Thanks for the output.  Good to know that it at least works when you use `-4`.

When you encountered the error originally, what command line options were you using?

**Comment by Zaptyp** [comment] 2023-04-01 11:44
@jtesta So I'm supposed to assume it's gonna be fixed? Because this happens when the server blocks the ability to use ICMP protocol.

**Comment by jtesta** [comment] 2023-08-25 19:23
@Zaptyp: I just re-examined this issue, but I still can't find anything wrong with the code itself.  By default, it tries to resolve the target using `socket.getaddrinfo()` with the `AF_UNSPEC` family (see https://github.com/jtesta/ssh-audit/blob/master/src/ssh_audit/ssh_socket.py#L90).  That properly works when an IPv4 target is given.

I'd love to be able to fix this issue if it actually exists in the code, but sadly, I cannot reproduce it.  If you can provide a target that you still see this behavior against, please let me know!  If you'd like to send it to me privately, you can use my email: jtesta at-sign positronsecurity dot com.  Otherwise, I suppose I'll have to close this issue.

**Closed by jtesta** 2023-08-25 19:23 UTC
