### ISSUE TITLE
LookupError: unknown encoding: idna

### ISSUE THREAD

**Issue by kastahl** [jtesta/ssh-audit#152] opened 2022-10-13 10:55 UTC
I get an exception when scanning some targets using targets file. When scanning these targets manually, it works fine.

I'm using the ssh-audit.exe in Version 2.5 on a Windows 10 VM.
For me it looks like to be an issue of missing import: `import encodings.idna`

An exception occurred while scanning 10.2xx.xx.xx:22:
Traceback (most recent call last):
File "ssh-audit.py", line 1017, in target_worker_thread
File "ssh-audit.py", line 842, in audit
File "ssh_socket.py", line 155, in connect
File "ssh_socket.py", line 85, in _resolve
File "socket.py", line 953, in getaddrinfo
LookupError: unknown encoding: idna

--------------------------------------------------------------------------------

An exception occurred while scanning 10.2xx.xxx.xx:22:
Traceback (most recent call last):
  File "ssh-audit.py", line 1017, in target_worker_thread
  File "ssh-audit.py", line 842, in audit
  File "ssh_socket.py", line 155, in connect
  File "ssh_socket.py", line 85, in _resolve
  File "socket.py", line 953, in getaddrinfo
LookupError: unknown encoding: idna

--------------------------------------------------------------------------------

An exception occurred while scanning 10.2xx.xxx.xx:22:
Traceback (most recent call last):
  File "ssh-audit.py", line 1017, in target_worker_thread
  File "ssh-audit.py", line 842, in audit
  File "ssh_socket.py", line 155, in connect
  File "ssh_socket.py", line 85, in _resolve
  File "socket.py", line 953, in getaddrinfo
LookupError: unknown encoding: idna

--------------------------------------------------------------------------------

An exception occurred while scanning 10.2xx.xx.xx:22:
Traceback (most recent call last):
  File "ssh-audit.py", line 1017, in target_worker_thread
  File "ssh-audit.py", line 842, in audit
  File "ssh_socket.py", line 155, in connect
  File "ssh_socket.py", line 85, in _resolve
  File "socket.py", line 953, in getaddrinfo
LookupError: unknown encoding: idna

--------------------------------------------------------------------------------

An exception occurred while scanning 10.2xx.xxx.xx:22:
Traceback (most recent call last):
  File "ssh-audit.py", line 1017, in target_worker_thread
  File "ssh-audit.py", line 842, in audit
  File "ssh_socket.py", line 155, in connect
  File "ssh_socket.py", line 85, in _resolve
  File "socket.py", line 953, in getaddrinfo
LookupError: unknown encoding: idna

**Comment by thecliguy** [comment] 2022-10-13 19:24
@kastahl I have done some debugging and it looks like this problem is very specfic to the executable version of ssh-audit for Windows which is built using [pyinstaller](https://pyinstaller.org/en/stable/).

Please can you tell me, how many targets do you have in your targets file?

**Comment by kastahl** [comment] 2022-10-14 07:31
> @kastahl I have done some debugging and it looks like this problem is very specfic to the executable version of ssh-audit for Windows which is built using [pyinstaller](https://pyinstaller.org/en/stable/).
> 
> Please can you tell me, how many targets do you have in your targets file?

@thecliguy There just 9 targets in the targets file. The first 4 targets will be processed.

**Comment by thecliguy** [comment] 2022-10-14 07:53
@kastahl Are all 9 targets scanned successfully if you use the parameter `--threads=1`?

EG:

```
C:\temp\ssh-audit.exe --targets=hosts.txt --threads=1
```

**Comment by kastahl** [comment] 2022-10-14 13:41
> --threads=1

@thecliguy That works and all targets will be processed now. :)

**Comment by thecliguy** [comment] 2022-10-14 14:04
@kastahl Thanks for testing, much appreciated.

This confirms my suspicion that the problem relates to multithreading and appears only to affect the Windows executable version of ssh-audit.

Please leave this ticket open because although we now have a workaround (which is to avoid multiple threads), there is still a bug that needs to be fixed properly.

**Comment by jtesta** [comment] 2022-10-15 02:42
Thanks for helping with this, @thecliguy.  I'll investigate this
further next time I do testing on my Windows machine.

**Comment by jtesta** [comment] 2023-03-24 19:46
Looks like this is related to the following CPython bug: https://github.com/python/cpython/issues/73474

Someone in that thread suggested a workaround.  I'll give that a try.

**Comment by thecliguy** [comment] 2023-04-25 18:00
@jtesta : I've just read #152... When the workaround is invoked, a warning is printed advising that: _"...Multi-threaded scanning can be enabled by installing the idna module (pip install idna)"_.

This problem is only known to occur with the executable version of ssh-audit for Windows which is built using [pyinstaller](https://pyinstaller.org/en/stable/)... 

My understanding is that all dependencies including the Python interpreter are bundled within the Windows executable. Therefore, a Windows user doesn't need Python to be installed. So on that basis, I don't think the advice of installing the idna module is applicable or actionable when dealing with the Windows executable because it doesn't interact with a locally installed copy of Python.

**Comment by jtesta** [comment] 2023-04-27 02:01
@thecliguy: I thought the problem happened in both the packaged executable as well as with the unpackaged source files.  But when I went back and tried to reproduce both cases, I could no longer trigger the crash.  I've since upgraded my build machine from Python v3.9 to v3.11, and I suspect that this addressed the root cause (!).  Hence, I've commented out the workaround that I applied to the source tree.

If anyone notices this same crash using the latest commit in `master`, please chime in!

**Comment by oam7575** [comment] 2023-05-15 01:18
I have just carried out some basic testing with a variety of different python versions. Details below

Windows 10 22H2
ssh-audit master
command : "python.exe h:\GIT\ssh-audit\ssh-audit.py -T h:\GIT\ssh-audit\test.txt --threads=4"
text file contains 2x hosts with 2x formats for each host.
1x will succeed and 1x will fail for each ( deliberate incorrect port number )

* Python 3.6.2 - Appears OK - No Errors
* Python 3.7.0 - Appears OK - No Errors
* Python 3.8.0 - Appears OK - No Errors
* Python 3.9.13 - Appears OK - No Errors
* Python 3.10.11 - Appears OK - No Errors
* Python 3.11.3 - Appears OK - No Errors

**Comment by jtesta** [comment] 2023-06-19 17:05
@oam7575 : thanks for doing all this testing!  Does the precompiled Windows executable have any trouble on your system?

**Comment by jtesta** [comment] 2023-06-21 17:07
@kastahl : I think this issue is fixed in the Windows executable released in v2.9.0.  If you're able to test it on your system, that would be a big help!  Thanks!

**Comment by kastahl** [comment] 2023-06-26 11:32
@jtesta I will try to test it in the next days. Will give feedback asap.

**Comment by jtesta** [comment] 2023-08-25 19:26
@kastahl: Well, I suppose I'll close this issue, since v2.9.0 has been out for nearly 4 months, and no one has reported any problems with it.  If you do run into the problem again, though, please re-open this issue.

Thanks for reporting it!

**Closed by jtesta** 2023-08-25 19:26 UTC
